# Generated by Django 5.1.4 on 2024-12-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stocks_available',
            field=models.IntegerField(default=0),
        ),
    ]
