# Generated by Django 5.1.4 on 2025-01-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_seller_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='location',
            field=models.CharField(default='India', max_length=255),
        ),
    ]
