# Generated by Django 5.1.4 on 2025-01-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_seller_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
