# Generated by Django 5.1.4 on 2025-01-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_seller_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
