# Generated by Django 5.1.4 on 2025-01-06 12:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_product_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='seller_gst',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number in the format: 22ABCDE1234F1Z5', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}$')]),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_address', models.CharField(max_length=255)),
                ('buyer_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('quantity', models.IntegerField(default=0)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('sold_date', models.DateField(auto_now_add=True)),
                ('buyer_gst', models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number in the format: 22ABCDE1234F1Z5', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}$')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.product')),
            ],
        ),
    ]
