# Generated by Django 5.1.4 on 2025-01-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_purchase_seller_gst_sales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller',
            new_name='Merchants',
        ),
        migrations.RenameField(
            model_name='merchants',
            old_name='seller_address',
            new_name='merchant_address',
        ),
        migrations.RenameField(
            model_name='merchants',
            old_name='seller_name',
            new_name='merchant_name',
        ),
        migrations.RenameField(
            model_name='merchants',
            old_name='seller_number',
            new_name='merchant_number',
        ),
    ]
