# Generated by Django 5.1.4 on 2025-01-06 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_rename_seller_merchants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='seller_gst',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='buyer_gst',
        ),
        migrations.AddField(
            model_name='merchants',
            name='merchant_gst',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number in the format: 22ABCDE1234F1Z5', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}$')]),
        ),
    ]
