# Generated by Django 5.1.4 on 2025-01-06 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_remove_purchase_seller_gst_remove_sales_buyer_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='buyer_address',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='buyer_number',
        ),
        migrations.AddField(
            model_name='sales',
            name='buyer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='models.merchants'),
        ),
    ]
