# Generated by Django 5.1.4 on 2025-01-06 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_remove_sales_buyer_address_remove_sales_buyer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.merchants'),
        ),
    ]
