# Generated by Django 5.0.4 on 2024-05-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0002_rename_user_role_purchase_purchaser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRolesSalesMen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('purchaser', 'Purchaser'), ('salesperson', 'Sales Personnel')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='purchaser',
        ),
        migrations.DeleteModel(
            name='sales_men',
        ),
    ]
