# Generated by Django 5.0.4 on 2024-05-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('product_id', models.IntegerField()),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
