# Generated by Django 5.0.4 on 2024-05-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_component', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='added_date',
            new_name='product_date',
        ),
    ]
