# Generated by Django 5.0.4 on 2024-05-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_component', '0002_rename_added_date_productlist_product_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.TextField()),
                ('stock_id', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
                ('stock_price', models.IntegerField()),
            ],
        ),
    ]
