# Generated by Django 5.0.4 on 2024-05-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_component', '0003_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
